FROM node:12-alpine

RUN apk update && apk upgrade && apk add bash

USER root
WORKDIR /app/
COPY . /app

RUN yarn cache clean && \
    rm -rf node_modules && \
    yarn install

EXPOSE 4200
ENTRYPOINT ["/bin/bash", "-l", "-c"]
CMD [ "yarn run ng serve --host 0.0.0.0 --port 4200" ]
