# Generated by Django 3.2.9 on 2022-01-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncjoblog',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
