# Generated by Django 3.2.9 on 2022-08-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asyncjoblog_last_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsyncJobLog',
        ),
    ]
