---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sniper-frontend
  labels:
    app: sniper-frontend
    part-of: pdpj
spec:
  selector:
    matchLabels:
      app: sniper-frontend
      part-of: pdpj
  template:
    metadata:
      labels:
        app: sniper-frontend
        part-of: pdpj
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: sniper-frontend
                  part-of: pdpj
              topologyKey: kubernetes.io/hostname
      containers:
      - name: sniper-frontend
        image: registry.cnj.jus.br/pdpj/sniper-frontend:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: America/Sao_Paulo
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 6
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        startupProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 20
          periodSeconds: 30
          timeoutSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: sniper-frontend-config
          mountPath: /usr/share/nginx/html/assets/config
          readOnly: true
      imagePullSecrets:
      - name: registry-cnj
      volumes:
      - name: sniper-frontend-config
        configMap:
          name: sniper-frontend-config
...
---
apiVersion: v1
kind: Service
metadata:
  name: sniper-frontend
  labels:
    app: sniper-frontend
    part-of: pdpj
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
  selector:
    app: sniper-frontend
    part-of: pdpj
...
