---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sniper-frontend-config
  labels:
    app: sniper-frontend
    part-of: pdpj
data:
  env.js: |
    (function (window) {
      window.__env = window.__env || {};
      window.__env.production = false;
      window.__env.nome = "Sniper";
      window.__env.descricao = "Sistema Nacional de Investigação Patrimonial e Recuperação de Ativos";
      window.__env.apiUrl = "https://sniper-api.stg.pdpj.jus.br/v1",
      window.__env.ssoUrl = "https://sso.stg.cloud.pje.jus.br/auth/",
      window.__env.realm = "pje",
      window.__env.clientId = "sniper-frontend",
      window.__env.redirectUri = "https://sniper.stg.pdpj.jus.br"
    }(this));

...
